Repository digital-splash/PHP-Services, pull requests merged in 2023-05, with the labels that each got.

#17 Dg 00017 image change ratio class
  composer.json
  composer.lock
  src/Microservices/Media/Helpers/Ratio.php
  src/Microservices/Media/Helpers/Upload.php
  tests/Manual/Microservices/Media/Helpers/upload-files.php
Labels: Enhancement, New Feature, Status: WIP

#18 DG 00019 convert image to webp
  src/Helpers/Helper.php
  src/Microservices/Media/Helpers/ConvertType.php
  src/Microservices/Media/Helpers/Media.php
  src/Microservices/Media/Helpers/Ratio.php
  src/Microservices/Media/Helpers/Upload.php
  tests/Manual/Microservices/Media/Helpers/upload-files.php
Labels: Enhancement, New Feature, Approved: Code

#19 DG 00018 image resize class
  src/Microservices/Media/Helpers/ConvertType.php
  src/Microservices/Media/Helpers/Ratio.php
  src/Microservices/Media/Helpers/Resize.php
  src/Microservices/Media/Helpers/Upload.php
  src/Microservices/Media/Helpers/UploadQueue.php
  src/Microservices/Media/Interface/IImageModify.php
  src/Microservices/Media/Models/FacebookImage.php
  src/Microservices/Media/Models/Image.php
  tests/Manual/Microservices/Media/Helpers/upload-files.php
  tests/PhpUnits/Microservices/Media/Helpers/ConvertTypeTest.php
  tests/PhpUnits/Microservices/Media/Helpers/RatioTest.php
Labels: Enhancement, New Feature, Approved: Code

#23 DG-00023 media-unit-tests-2
  src/Exceptions/Media/InvalidExtensionException.php
  src/Microservices/Language/Mappings/Exception.json
  src/Microservices/Media/Helpers/ConvertType.php
  src/Microservices/Media/Helpers/Media.php
  src/Microservices/Media/Helpers/Ratio.php
  src/Microservices/Media/Helpers/Resize.php
  src/Microservices/Media/Models/File.php
  tests/PhpUnits/Microservices/Media/Helpers/ConvertTypeTest.php
  tests/PhpUnits/Microservices/Media/Helpers/MediaTest.php
  tests/PhpUnits/Microservices/Media/Helpers/RatioTest.php
  tests/PhpUnits/Microservices/Media/Helpers/ResizeTest.php
  tests/PhpUnits/Microservices/Media/Helpers/UploadQueueTest.php
  tests/PhpUnits/Microservices/Media/Models/FileTest.php
Labels: Enhancement, Approved: Code

#24 DG-00024 - Helper::DeleteFolderAndAllFiles
  src/Helpers/Helper.php
  tests/PhpUnits/Helpers/HelperTest.php
  tests/PhpUnits/Microservices/Media/Helpers/UploadQueueTest.php
  tests/_CommonFiles/Recursive/Folder1/Folder1-1/Folder1-1-1/file.html
  tests/_CommonFiles/Recursive/Folder1/Folder1-1/file.html
  tests/_CommonFiles/Recursive/Folder1/Folder1-2/file.html
  tests/_CommonFiles/Recursive/Folder2/Folder2-1/file.html
  tests/_CommonFiles/Recursive/Folder2/Folder2-2/file.html
Labels: Enhancement, New Feature, Status: WIP

#25 DG-00025 Notification Manager
  composer.json
  composer.lock
  src/Microservices/Media/Helpers/ConvertType.php
  src/Microservices/Media/Helpers/Ratio.php
  src/Microservices/Media/Helpers/Resize.php
  src/Microservices/Media/Interfaces/IImageModify.php
  src/Microservices/Notification/Helpers/Email/Email.php
  src/Microservices/Notification/Helpers/Email/PhpMailer.php
  src/Microservices/Notification/Helpers/MobileNotification.php
  src/Microservices/Notification/Helpers/SMS.php
  src/Microservices/Notification/Helpers/WebNotification.php
  src/Microservices/Notification/Interfaces/IEmail.php
  src/Microservices/Notification/Interfaces/INotification.php
  src/Microservices/Notification/Models/Email.php
  src/Microservices/Notification/Models/Recepient.php
  src/__/core/notification/Managers/Email/PhpMailerManager.php
  tests/Manual/Microservices/Media/Helpers/upload-files.php
  tests/Manual/Microservices/Notification/Helpers/email-testing.php
  tests/PhpUnits/Helpers/AntiHackTest.php
Labels: Enhancement, Approved: Code
