Repository digital-splash/PHP-Services, pull requests merged in 2023-04, with the labels that each got.

#8 DG-00007 Initial commit adding querybuilder
  src/Exceptions/Database/DatabaseInvalidConnectorException.php
  src/Helpers/Helper.php
  src/Microservices/Database/Helpers/DBCommon.php
  src/Microservices/Database/Helpers/DBHelper.php
  src/Microservices/Database/Models/DBCredentials.php
  src/Microservices/Database/Models/DBSettings.php
  src/Microservices/Database/Models/DatabaseCredentials.php
  src/Microservices/Database/MySQL/Helpers/DBConnector.php
  src/Microservices/Database/MySQL/Helpers/PDODataDB.php
  src/Microservices/Database/MySQL/Helpers/PDOStatementWrapper.php
  src/Microservices/Database/MySQL/Helpers/QueryBuilder.php
  src/Microservices/Language/Mappings/Exception.json
  tests/PhpUnits/Helpers/HelperTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Helpers/QueryBuilderTest.php
Labels: New Feature, Status: WIP

#9 DG-00010 Fix Composer and Namespace
  LICENSE
  README.md
  composer.json
  src/Renders/ContentGenerator/Accordion/AccordionElement.html
  src/Renders/ContentGenerator/Accordion/Main.html
  src/Renders/ContentGenerator/Accordion/scripts.js
  src/Renders/ContentGenerator/Accordion/styles.css
  src/Renders/ContentGenerator/Table/Main.html
  src/Renders/ContentGenerator/Table/scripts.js
  src/Renders/ContentGenerator/Table/styles.css
  src/Renders/ContentGenerator/Tabs/Main.html
  src/Renders/ContentGenerator/Tabs/TopTab.html
  src/Renders/ContentGenerator/Tabs/scripts.js
  src/Renders/ContentGenerator/Tabs/styles.css
  src/__/core/notification/Handlers/Notification_MainHandler.php
  src/__/core/notification/Handlers/ResendVerificationEmailHandler.php
  tests/PhpUnits/Helpers/HelperTest.php
  tests/PhpUnits/Helpers/MetaSeoTest.php
  tests/PhpUnits/Helpers/ServerCacheTest.php
  tests/PhpUnits/Helpers/ValidatorTest.php
  tests/PhpUnits/Microservices/Accounting/Helpers/CurrencyTest.php
  tests/PhpUnits/Microservices/Language/Helpers/LanguageTest.php
  tests/PhpUnits/Microservices/Language/Helpers/TranslateTest.php
  tests/_CommonFiles/MetaSeo/header.html
  tests/_CommonFiles/Upload/test.txt
  tests/_CommonFiles/testGetJsonContentFromFileAsArraySuccess.json
  utils/extensions/config/VSCode.md
Labels: Enhancement, Approved: Code

#10 DG-00009 Query Builder Improvements
  src/Microservices/Database/MySQL/Helpers/QueryBuilder.php
  tests/PhpUnits/Helpers/HelperTest.php
  tests/PhpUnits/Helpers/ValidatorTest.php
  tests/PhpUnits/Microservices/Accounting/Helpers/CurrencyTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Helpers/QueryBuilderTest.php
Labels: Enhancement, Approved: Code

#11 DG-00012 Query Builder Models
  src/Microservices/Database/MySQL/Helpers/QueryBuilder.php
  src/Microservices/Database/MySQL/Models/Base/IndexedArray.php
  src/Microservices/Database/MySQL/Models/Base/NonIndexedArray.php
  src/Microservices/Database/MySQL/Models/Base/SingleValue.php
  src/Microservices/Database/MySQL/Models/Binds.php
  src/Microservices/Database/MySQL/Models/Data.php
  src/Microservices/Database/MySQL/Models/Group.php
  src/Microservices/Database/MySQL/Models/Having.php
  src/Microservices/Database/MySQL/Models/Join.php
  src/Microservices/Database/MySQL/Models/Limit.php
  src/Microservices/Database/MySQL/Models/Offset.php
  src/Microservices/Database/MySQL/Models/Order.php
  src/Microservices/Database/MySQL/Models/Sql.php
  src/Microservices/Database/MySQL/Models/Where.php
  tests/PhpUnits/Microservices/Database/MySQL/Helpers/QueryBuilderTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/Base/IndexedArrayTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/Base/NonIndexedArrayTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/Base/SingleValueTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/BindsTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/DataTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/GroupTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/HavingTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/JoinTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/LimitTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/OffsetTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/OrderTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/SqlTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/WhereTest.php
Labels: Enhancement, Approved: Code

#14 DG-00012 => removing done comments
  src/Microservices/Database/MySQL/Models/Binds.php
  src/Microservices/Database/MySQL/Models/Join.php
Labels: Duplicate, Approved: Code

#13 DG 00011 query builder improvements
  src/Microservices/Database/MySQL/Models/Base/NonIndexedArray.php
  src/Microservices/Database/MySQL/Models/Binds.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/Base/NonIndexedArrayTest.php
  tests/PhpUnits/Microservices/Database/MySQL/Models/BindsTest.php
Labels: Duplicate, Enhancement

#15 DG-00008 fix functions parameters to be the same as php
  src/Exceptions/Base/BaseException.php
  src/Exceptions/InvalidArgumentException.php
  src/Helpers/Helper.php
  src/Helpers/MachineInfo.php
  src/Helpers/MetaSeo.php
  src/Helpers/Script.php
  src/Helpers/ServerCache.php
  src/Helpers/Style.php
  src/Microservices/Database/Helpers/DBCommon.php
  src/Microservices/Database/Helpers/DBHelper.php
  src/Microservices/Database/MySQL/Helpers/PDODataDB.php
  src/Microservices/Database/MySQL/Helpers/PDOStatementWrapper.php
  src/Microservices/Database/MySQL/Helpers/QueryBuilder.php
  src/Microservices/Database/MySQL/Models/Base/IndexedArray.php
  src/Microservices/Database/MySQL/Models/Base/NonIndexedArray.php
  src/Microservices/Date/Helpers/Date.php
  src/Microservices/Language/Helpers/Language.php
  src/Microservices/Language/Helpers/Translate.php
  src/Microservices/Media/Helpers/Media.php
  src/Renders/Accordion.php
  src/Renders/Table.php
  src/Renders/Tabs.php
  src/__/core/Database.php
  src/__/core/OnlinePayment/PayFast/PayFast.php
  src/__/core/notification/Managers/Email/PhpMailerManager.php
  src/__/core/notification/Managers/WebNotification/WebNotificationManager.php
  src/__/database/Address.php
  src/__/database/Cart.php
  src/__/database/views/VProduct.php
  tests/PhpUnits/Helpers/HelperTest.php
Labels: Enhancement, Approved: Code
