Repository digital-splash/PHP-Services, pull requests merged in 2023-06, with the labels that each got.

#31 DG-00030 Add Basic Docker
  .gitattributes
  .htaccess
  Makefile
  composer.json
  docker-compose.yml
  dockerfiles/.env
  dockerfiles/base-container/Dockerfile
  tests/Manual/info.php
  tests/PhpUnits/README.md
Labels: New Feature, Approved: Code

#30 DG-00029-env-configuration
  .gitignore
  composer.json
  dgsplash.phpservices.env.example.json
  env.php
  src/Exceptions/ConfigurationNotFound.php
  src/Exceptions/InvalidConfiguration.php
  src/Microservices/Language/Mappings/Exception.json
  src/Microservices/Notification/Helpers/Email/PhpMailer.php
  tests/Manual/Microservices/Notification/Helpers/email-testing.php
Labels: Enhancement, New Feature, Status: WIP

#32 DG-00032 - Docker Config
  env.php
  src/Exceptions/Configuration/ConfigurationNotFound.php
  src/Exceptions/Configuration/InvalidConfiguration.php
  src/Microservices/Language/Mappings/Exception.json
Labels: Documentation, Enhancement, New Feature, Approved: Code

#33 DG-00034-email-template-variables
  dgsplash.phpservices.env.example.json
  env.php
  src/Microservices/Notification/Helpers/Email/PhpMailer.php
  src/Microservices/Notification/Models/Email.php
  src/Microservices/Notification/Models/EmailConfiguration.php
  src/Microservices/Notification/Models/Notification.php
  src/Microservices/Notification/Models/Template.php
  src/Microservices/Notification/Templates/Email/Main/boxed_with_button.html
  src/Models/Tenant.php
  tests/Manual/Microservices/Notification/Helpers/email-testing.php
  tests/PhpUnits/Microservices/Notification/Models/TemplateTest.php
  tests/PhpUnits/Microservices/Notification/Templates/Email/Main/boxed_with_button.html
Labels: Enhancement, Help Wanted, New Feature, Status: WIP

#35 DG-00033-docker-config
  docker-compose.yml
  dockerfiles/base-container/Dockerfile
  dockerfiles/base-container/php.ini
  src/Microservices/Language/Helpers/Translate.php
  tests/Manual/Microservices/Notification/Helpers/email-testing.php
Labels: Documentation, Enhancement, New Feature, Approved: Code

#34 DG-00035-email-template
  dgsplash.phpservices.env.example.json
  env.php
  src/Microservices/Notification/Models/Template.php
  tests/Manual/Microservices/Notification/Helpers/email-testing.php
Labels: Enhancement, Help Wanted, Status: WIP
